name: CloverChat
version: ${version}
main: com.slyph.cloverchat.CloverChatPlugin
api-version: 1.16
folia-supported: true
authors: [slyph]
softdepend: [PlaceholderAPI]
description: Настраиваемый чат для сервера

commands:
  m:
    description: Отправить личное сообщение
    usage: /m <ник> <сообщение>
    permission: cloverchat.pm
  cloverchatreload:
    description: Перезагрузить CloverChat
    usage: /cloverchatreload confirm
    permission: cloverchat.command.reload

permissions:
  cloverchat.chat.use:
    description: Разрешает писать в чат
    default: true
  cloverchat.pm:
    description: Разрешает использовать команду /m
    default: true
  cloverchat.pm.quick:
    description: Разрешает быстрое ЛС по ПКМ на игрока
    default: true
  cloverchat.pm.bypass.cooldown:
    description: Обходит кулдаун личных сообщений
    default: op
  cloverchat.command.reload:
    description: Разрешает перезагружать плагин
    default: op
  cloverchat.commandcooldown.bypass:
    description: Обходит общий кулдаун команд
    default: op
